
// Objective-C API for talking to the following Go packages
//
//	github.com/goany/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Unichain_FRAMEWORK_H__
#define __Unichain_FRAMEWORK_H__

#include "Unichain.objc.h"
#include "Universe.objc.h"

#endif
