// Objective-C API for talking to github.com/inwecrypto/mobilesdk/ethmobile Go package.
//   gobind -lang=objc github.com/inwecrypto/mobilesdk/ethmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Ethmobile_H__
#define __Ethmobile_H__

#import "ref.h"
#include "Universe.objc.h"


@class EthmobileWallet;

/**
 * Wallet neo mobile wallet
 */
@interface EthmobileWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Address get wallet address
 */
- (NSString*)address;
/**
 * Mnemonic gete mnemonic string
 */
- (NSString*)mnemonic:(NSString*)lang error:(NSError**)error;
/**
 * ToKeyStore write wallet to keystore format string
 */
- (NSString*)toKeyStore:(NSString*)password error:(NSError**)error;
/**
 * Transfer transfer eth to target address
 */
- (NSString*)transfer:(NSString*)nonce to:(NSString*)to amount:(NSString*)amount gasPrice:(NSString*)gasPrice gasLimits:(NSString*)gasLimits error:(NSError**)error;
/**
 * TransferERC20 transfer eth to target address
 */
- (NSString*)transferERC20:(NSString*)contract nonce:(NSString*)nonce to:(NSString*)to amount:(NSString*)amount gasPrice:(NSString*)gasPrice gasLimits:(NSString*)gasLimits error:(NSError**)error;
@end

/**
 * FromKeyStore create wallet from keystore
 */
FOUNDATION_EXPORT EthmobileWallet* EthmobileFromKeyStore(NSString* ks, NSString* password, NSError** error);

/**
 * FromMnemonic create wallet from mnemonic
 */
FOUNDATION_EXPORT EthmobileWallet* EthmobileFromMnemonic(NSString* mnemonic, NSString* lang, NSError** error);

/**
 * FromPrivateKey .
 */
FOUNDATION_EXPORT EthmobileWallet* EthmobileFromPrivateKey(NSData* privateKey, NSError** error);

/**
 * New create a new wallet
 */
FOUNDATION_EXPORT EthmobileWallet* EthmobileNew(NSError** error);

#endif
