
// Objective-C API for talking to the following Go packages
//
//	github.com/inwecrypto/neo-wallet-sdk/mobile
//	github.com/goany/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Neomobile_FRAMEWORK_H__
#define __Neomobile_FRAMEWORK_H__

#include "Neomobile.objc.h"
#include "Unichain.objc.h"
#include "Universe.objc.h"

#endif
