// Objective-C API for talking to github.com/inwecrypto/neo-wallet-sdk/mobile Go package.
//   gobind -lang=objc github.com/inwecrypto/neo-wallet-sdk/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Neomobile_H__
#define __Neomobile_H__

@import Foundation;
#include "Universe.objc.h"


@class NeomobileTx;
@class NeomobileWallet;

/**
 * Tx neo rawtx wrapper
 */
@interface NeomobileTx : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)data;
- (void)setData:(NSString*)v;
- (NSString*)id_;
- (void)setID:(NSString*)v;
@end

/**
 * Wallet neo mobile wallet
 */
@interface NeomobileWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
/**
 * Address get wallet address
 */
- (NSString*)address;
/**
 * CreateAssertTx create assert transfer raw tx
 */
- (NeomobileTx*)createAssertTx:(NSString*)assert from:(NSString*)from to:(NSString*)to amount:(double)amount unspent:(NSString*)unspent error:(NSError**)error;
/**
 * CreateClaimTx create claim tx
 */
- (NeomobileTx*)createClaimTx:(double)amount address:(NSString*)address unspent:(NSString*)unspent error:(NSError**)error;
/**
 * Mnemonic gete mnemonic string
 */
- (NSString*)mnemonic:(NSError**)error;
/**
 * ToKeyStore write wallet to keystore format string
 */
- (NSString*)toKeyStore:(NSString*)password error:(NSError**)error;
@end

/**
 * FromKeyStore create wallet from keystore
 */
FOUNDATION_EXPORT NeomobileWallet* NeomobileFromKeyStore(NSString* keystore, NSString* password, NSError** error);

/**
 * FromMnemonic create wallet from mnemonic
 */
FOUNDATION_EXPORT NeomobileWallet* NeomobileFromMnemonic(NSString* mnemonic, NSError** error);

/**
 * FromWIF create wallet from wif
 */
FOUNDATION_EXPORT NeomobileWallet* NeomobileFromWIF(NSString* wif, NSError** error);

/**
 * New create a new wallet
 */
FOUNDATION_EXPORT NeomobileWallet* NeomobileNew(NSError** error);

#endif
